name: Lint
on: [push]
jobs:
  execute_eslint_linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: yarn lint:fix
